CENTER_OFFSET = 0

OUTSIDE_X = 35
OUTSIDE_Y = 300
OUTSIDE_WIDTH = 730
OUTSIDE_HEIGHT = 260

INSIDE_X = 40
INSIDE_Y = 305
INSIDE_WIDTH = 720
INSIDE_HEIGHT = 250

LETTERS_X = 40
LETTERS_Y = 305
LETTERS_WIDTH = 45
LETTERS_HEIGHT = 250

SINGLE_NUM_WIDTH = 25
SINGLE_NUM_HEIGHT = 25
SINGLE_NUM_RPOS_X = 10
SINGLE_NUM_RPOS_Y = 5

DOUBLE_NUM_WIDTH = 15
DOUBLE_NUM_HEIGHT = 25
DOUBLE_NUM_RPOS_X = [5,25]
DOUBLE_NUM_RPOS_Y = [10,10]

BOARD_NUMBERS_POS_X = INSIDE_X + 45
BOARD_NUMBERS_POS_Y = INSIDE_Y
BOARD_NUMBERS_WIDTH = 45
BOARD_NUMBERS_HEIGHT = 50

HOPPER_OUTSIDE_X = 555
HOPPER_OUTSIDE_Y = 40
HOPPER_OUTSIDE_WIDTH = 210
HOPPER_OUTSIDE_HEIGHT = 240

HOPPER_INSIDE_X = 560
HOPPER_INSIDE_Y = 45
HOPPER_INSIDE_WIDTH = 200
HOPPER_INSIDE_HEIGHT = 230

HOPPER_LETTERS_X = HOPPER_INSIDE_X
HOPPER_LETTERS_Y = HOPPER_INSIDE_Y
HOPPER_LETTERS_WIDTH = HOPPER_INSIDE_WIDTH
HOPPER_LETTERS_HEIGHT = 50
HOPPER_IND_LETTERS_WIDTH = 40
HOPPER_IND_LETTERS_HEIGHT = 50

HOPPER_NUMBERS_X = [HOPPER_LETTERS_X,HOPPER_LETTERS_X +100]
HOPPER_NUMBERS_Y = HOPPER_LETTERS_Y + HOPPER_LETTERS_HEIGHT
HOPPER_NUMBERS_WIDTH = 100
HOPPER_NUMBERS_HEIGHT = 180

HOPPER_IND_NUMBERS_X = [100,200,300,400,500,600,700,800,900,1000]
HOPPER_IND_NUMBERS_Y = 0
HOPPER_IND_NUMBERS_WIDTH = 100
HOPPER_IND_NUMBERS_HEIGHT = 180



# For each number, use the following formula:
# R is row, C is column, num is num
# POSITION_X[num] = BOARD_NUMBERS_X + (num % 15) * BOARD_NUMBERS_WIDTH
# POSITION_Y[num] = BOARD_NUMBERS_Y + int(num / 15) * BOARD_NUMBERS_HEIGHT





